[package]
name = "opencad"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.18.0"
bevy_egui = "0.39.0"
bevy_panorbit_camera = "0.34.0"
chrono = "0.4.43"
dirs = "6.0.0"
egui_ltreeview = "0.6.0"
rfd = "0.17.2"
serde = "1.0.228"
serde_json = "1.0.149"
